### PR TITLE
Updated to Swift 4.2

### PR DESCRIPTION
**Pull request by batuhansk**

### CODE REVIEW

**Review by candostdagdeviren — CHANGES_REQUESTED** [review]
Hi @strawb3rryx7,
Thanks for the PR. But the CI is failing and the reason is it tries to use Xcode 9 with swift version 4.0. You need to update Swift version in the `.swift-version` file and update the Xcode version in Travis configuration file. Then, I guess the CI will be green again. 
Thanks!

**Comment by batuhansk** [comment]
Thanks for informing. Actually, I was aware about that. I'll update the .swift-version and Travis configuration for CI automation. ✋🏼

**Comment by batuhansk** [comment]
All of them is done. Ready to merge. 🙌🏼

**Review by candostdagdeviren — APPROVED** [review]

**Comment by candostdagdeviren** [comment]
Currently, I have some troubles with Cocoapods to publish this change. I will try to publish it in ~48 hours. Again, huge thanks for the contribution @strawb3rryx7 !

**Comment by candostdagdeviren** [comment]
Released!

screenshot 2018-09-19 at 00 34 45

**Pull request merged**
